version: '3.9'

networks:
  ergo-index-fund-backend:
    name: ergo-index-fund-backend
    driver: bridge

secrets:
  google_application_credentials:
    file: google_application_credentials.json

services:
  # Main application
  ergo-index-fund-backend:
    container_name: ergo-index-fund-backend
    build:
      context: .
      args:
        - OPENJDK_TAG=8u292
        - SBT_VERSION=1.5.4
    ports:
      - 8080:8080
    networks:
      - ergo-index-fund-backend
    secrets:
      - google_application_credentials
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google_application_credentials
